### PR TITLE
Ethernet mode

### PR DESCRIPTION
**Pull request by fermuch**
Hello! I've made this merge to support ethernet instead of wifi.

-----------------------------------

Before merging, if there is intention to merge (not sure if LAN support is inside this project scope), I'd like to point some things out:

* The setting `ETHERNET_PHY` expects a `network.LAN` object.  This is like this because are there [several settings](https://github.com/loboris/MicroPython_ESP32_psRAM_LoBo/blob/7dd4cba81af4ef682639eb2ed02ef3d33ea5f67a/MicroPython_BUILD/components/micropython/esp32/network_lan.c#L102-L109). I don't like how having an object on the settings looks like, and I am open to discussing what's the best way to handle these settings. **One thing to note:** these settings might vary a lot between platforms, as in, the ESP32 expects the interface to be connected in certain way, which might not be applicable for other boards, who might need extra parameters.

* I only tested this code on the [Olimex ESP32 Ethernet](https://github.com/OLIMEX/ESP32-GATEWAY), since it is the only board I have with ethernet.

* I only tested this code on the [ESP32 LoBo firmware](https://github.com/loboris/MicroPython_ESP32_psRAM_LoBo). It should work under vanilla ESP32 firmware, or other boards, but I did not have other boards at hand to flash and test.

### CODE REVIEW

**Comment by bodiroga** [comment]
Hi guys!

First of all, many thanks to all the contributors of this awesome project! I'm reading about micropython for the last two days and it is amazing, great work with microhomie! At the same time, I would like to thank @fermuch for his pull request!

Is there any interest in updating the PR to the latest master version? There are a couple of (small) conflicts that I could take care of, but first I would like to know if you are interested in merging it.

Best regards,

Aitor

**Comment by rroemhild** [comment]
Hi @fermuch,
Hi @bodiroga,

we have published the alpha release for the refactored Microhomie firmware with asyncio support and if you can update this PR we would be happy to merge it!

Best regards
Rafael

**Comment by bodiroga** [comment]
Hi @rroemhild!

I will look at it, but not until mid July, I'm very busy right now 😢 

Thanks for all your work and keep up with the good work!

**Comment by rroemhild** [comment]
Since Version 2, Microhomie use the wifi connection handler from Peter Hinch's mqtt async module. Therefore this must be implemented in the mqtt async module.

Will close this PR for now.

**Pull request closed without merging**
